User.create!(first_name: "Travis", last_name: "Knight", email: "travis@email.com", password: "password")
User.create!(first_name: "Chimbly", last_name: "Bimbly", email: "chimbly@email.com", password: "password")
User.create!(first_name: "Shaquille", last_name: "O'Neal", email: "shaquille@email.com", password: "password")

Category.create!(body_part: "Upper Body")
Category.create!(body_part: "Lower Body")
Category.create!(body_part: "Core")

Muscle.create!(name: "Chest")
Muscle.create!(name: "Back")
Muscle.create!(name: "Shoulders")
Muscle.create!(name: "Hamstrings")
Muscle.create!(name: "Quadriceps")
Muscle.create!(name: "Abs")

Exercise.create!(name: "Push-ups", category_id: 1, video_url: "http://www.youtube.com/embed/sBfW0tj9fqg", description: "A push-up is an exercise done laying with face, palms and toes facing down, keeping legs and back straight, extending arms straight to push body up and back down again. An example of a push-up is a great exercise that works the chest, shoulder and arm muscles.")
Exercise.create!(name: "Pull-ups", category_id: 1, video_url: "http://www.youtube.com/embed/3Eq4VF5SudM", description: "The pull-up is a closed-chain movement where the body is suspended by the hands and pulls up. As this happens, the elbows flex and the shoulders adduct and extend to bring the elbows to the torso.")
Exercise.create!(name: "Lunges", category_id: 2, video_url: "http://www.youtube.com/embed/-P9HIPp1QG4", description: "A lunge can refer to any position of the human body where one leg is positioned forward with knee bent and foot flat on the ground while the other leg is positioned behind. It is used by athletes in cross-training for sports, by weight-trainers as a fitness exercise, and by yogis as part of an asana regimen.")
Exercise.create!(name: "Deadlift", category_id: 2, video_url: "http://www.youtube.com/embed/T7-p5RBADIY", description: "Deadlift refers to the lifting of dead weight (weight without momentum), such as weights lying on the ground. It is one of the few standard weight training exercises in which all repetitions begin with dead weight. There are several positions one can approach when performing the deadlift, which include the conventional deadlift, squat, and sumo-deadlift. In most other lifts there is an eccentric (lowering of the weight) phase followed by the concentric (lifting of the weight) phase. During these exercises, a small amount of energy is stored in the stretched muscles and tendons in the eccentric phase if the lifter is not flexible beyond the range of motion. Although this exercise uses the hips and legs as the primary movers, it can just as easily be considered a back exercise.")
Exercise.create!(name: "Pallof Press", category_id: 3, video_url: "http://www.youtube.com/embed/nFspBRHke4w", description: "The Pallof Press is a core stabilization exercise that has broad application to strength, power, and functional fitness athletes. It can be performed in a movement prep protocol, or as a core accessory to improve strength and muscular endurance.")
Exercise.create!(name: "Front Squat", category_id: 2, video_url: "http://www.youtube.com/embed/m4ytaCJZpl0", description: "The Front Squat is a lower-body exercise that will strengthen your legs and hips, particularly your quads (thigh muscles) and glutes (butt muscles). Front Squats are similar to Back Squats, however the barbell is placed across the front side of your shoulders instead of your upper back.")
Exercise.create!(name: "Overhead Press", category_id: 1, video_url: "http://www.youtube.com/embed/xe19t2_6yis", description: "The Overhead Press is a full body, compound exercise. Your shoulders and arms press the weight over your head while your legs, lower back and abs balance you. The Overhead Press is one of the best exercises to build strong, muscular and healthy shoulders with bigger arms")
Exercise.create!(name: "Plank", category_id: 3, video_url: "http://www.youtube.com/embed/pvIjsG5Svck", description: "Plant hands directly under shoulders (slightly wider than shoulder width) like you're about to do a pushup. Ground toes into the floor and squeeze glutes to stabilize your body. Neutralize your neck and spine by looking at a spot on the floor about a foot beyond your hands. Think about squeezing your elbows to your knees and your knees to your elbows.")

Work.create!(exercise_id: 1, muscle_id: 1, category_id: 1)
Work.create!(exercise_id: 1, muscle_id: 3, category_id: 1)
Work.create!(exercise_id: 2, muscle_id: 2, category_id: 1)
Work.create!(exercise_id: 3, muscle_id: 4, category_id: 2)
Work.create!(exercise_id: 3, muscle_id: 5, category_id: 2)
Work.create!(exercise_id: 5, muscle_id: 6, category_id: 3)

Workout.create!(user_id: 1, exercise_id: 1, sets: 3, reps: 10, weight: "Body Weight")
Workout.create!(user_id: 1, exercise_id: 2, sets: 3, reps: 8, weight: "Body Weight")
Workout.create!(user_id: 1, exercise_id: 3, sets: 3, reps: 12, weight: "25")
Workout.create!(user_id: 1, exercise_id: 4, sets: 5, reps: 5, weight: "300")
Workout.create!(user_id: 1, exercise_id: 5, sets: 4, reps: 8, weight: "Red Band")

Complete.create!(workout_id: 1, exercise_id: 1, sets: 4, reps: 12, weight: "Body Weight")
Complete.create!(workout_id: 2, exercise_id: 2, sets: 3, reps: 5, weight: "Body Weight")
Complete.create!(workout_id: 3, exercise_id: 3, sets: 3, reps: 12, weight: "35")
Complete.create!(workout_id: 4, exercise_id: 4, sets: 5, reps: 12, weight: "340")
Complete.create!(workout_id: 5, exercise_id: 5, sets: 4, reps: 12, weight: "Purple Band")
